// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: src/v1/wallet/wallet.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "wallet";

export interface CreateWalletReq {
  userId: string;
  currency: string;
}

export interface Currency {
  code: string;
  name: string;
  symbol: string;
}

export interface CreateWalletRes {
  id: number;
  userId: string;
  currency: Currency | undefined;
}

export interface WalletResponseType {
  id: number;
  userId: string;
  totalBalance: number;
  availableBalance: number;
  status: string;
  createdAt: string;
  updatedAt?: string | undefined;
  currency?: Currency | undefined;
}

export interface GetWalletByUserIdReq {
  userId: string;
}

export interface GetWalletByIdReq {
  walletId: number;
}

export const WALLET_PACKAGE_NAME = "wallet";

export interface WalletServiceClient {
  createWallet(request: CreateWalletReq, metadata: Metadata, ...rest: any): Observable<CreateWalletRes>;

  getWalletByUserId(request: GetWalletByUserIdReq, metadata: Metadata, ...rest: any): Observable<WalletResponseType>;

  getWalletById(request: GetWalletByIdReq, metadata: Metadata, ...rest: any): Observable<WalletResponseType>;
}

export interface WalletServiceController {
  createWallet(
    request: CreateWalletReq,
    metadata: Metadata,
    ...rest: any
  ): Promise<CreateWalletRes> | Observable<CreateWalletRes> | CreateWalletRes;

  getWalletByUserId(
    request: GetWalletByUserIdReq,
    metadata: Metadata,
    ...rest: any
  ): Promise<WalletResponseType> | Observable<WalletResponseType> | WalletResponseType;

  getWalletById(
    request: GetWalletByIdReq,
    metadata: Metadata,
    ...rest: any
  ): Promise<WalletResponseType> | Observable<WalletResponseType> | WalletResponseType;
}

export function WalletServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createWallet", "getWalletByUserId", "getWalletById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WalletService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WalletService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WALLET_SERVICE_NAME = "WalletService";
